image: node:latest

Test:
  stage: build
  script: 
    - npm install
    - npm test

pages:
  script:
    - mkdir public
    - npm install
    - npm run build
    - cp -r prodDist/* public
  artifacts:
    paths:
      - public
  allow_failure: false
  only:
    - /^(master)|(release)$/
